version: '3.7'

services:
  app:
    image: network-understanding
    # volumes:
    #   - .:/app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      redis:
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - cache:/data
    # healthcheck:
    #   test: redis-cli ping

volumes:
  cache:
